name: Go Continuous Integration Continuous Delivery

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: Check out Code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '^1.15.5'
      - name: Run version check
        run: go version
      - name: Test main_test.go
        run: go test .
      - name: Install Dependencies
        id: InstallDeps
        run: |
          go get -u github.com/jstemmer/go-junit-report
                 
      - if: ${{failure()}}
        name: Create Issues
        uses: nashmaniac/create-issue-action@v1.1
        with:
          title: Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: workflow-failed
          body: Workflow failed for commit ${{github.sha}} @ ${{github.ref}}        
      - name: Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.5
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: report.xml
