name: README Info Update

on:
  push:
    branches: main
    tags: -v*
  pull_request:
    branches: 
      - '**'
  schedule:
    - cron: '0 0 * * *'


jobs:
  update-readme:
    name: GitHub README Generator
    runs-on: ubuntu-latest
    steps:
      - uses: th3c0d3br34ker/github-readme-info@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TIMEZONE: "Asia/Singapore"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_DAILY_COMMIT: "True"
          SHOW_WEEKLY_COMMIT: "True"
          SHOW_LANGUAGE: "True"
  gitIssueCreation:
    name: Git Creation Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Git Creation Demo
        uses: bryannice/gitactions-git-issue-creation@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_COMMIT_SHA: ${{ github.sha }}
          GITHUB_REPO_OWNER: 'gabrielleeyj'
          GITHUB_REPO_NAME: 'MyGoCalculator'
          GITHUB_ISSUE_TITLE: 'Issue Created for ${{ github.action }}'
          GITHUB_ISSUE_BODY: '${{ github.event }} has been record.'
